# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: galaga
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: to-do-list
service: to-do-list-backend

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  environment:
    COGNITO_ISSUER_URL: ${env:COGNITO_ISSUER_URL}
    COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}
    FRONTEND_URL: ${env:FRONTEND_URL}
    REDIRECT_URI_CALLBACK: ${env:REDIRECT_URI_CALLBACK}
    COGNITO_CLIENT_SECRET: ${env:COGNITO_CLIENT_SECRET}

package:
  excludeDevDependencies: true

functions:
  login:
    handler: functions/login.handler
    events:
      - http:
          path: login
          method: get
          cors: true

  callback:
    handler: functions/callback.handler
    events:
      - http:
          path: callback
          method: get
          cors: true

  logout:
    handler: functions/logout.handler
    events:
      - http:
          path: logout
          method: get
          cors: true
